"""Data models for the broadband QoS simulator."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class ScenarioType(str, Enum):
    """Ground-truth labels for simulated network conditions."""

    NORMAL = "normal"
    CONGESTION = "congestion"
    HIGH_LATENCY = "high_latency"
    PACKET_LOSS = "packet_loss"
    BANDWIDTH_LIMIT = "bandwidth_limit"
    OUTAGE = "outage"


class Severity(str, Enum):
    """Incident severity used by events and future NOC panels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass(frozen=True)
class NetworkNode:
    """Virtual broadband access node / service area."""

    node_code: str
    region: str
    access_technology: str
    service_tier_mbps: float
    subscriber_count: int
    baseline_latency_ms: float
    max_bandwidth_mbps: float
    baseline_jitter_ms: float = 2.5
    baseline_packet_loss_pct: float = 0.05
    baseline_signal_quality: float = 92.0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class QoSMeasurement:
    """Single timestamped QoS sample for one node."""

    node_code: str
    timestamp: datetime
    latency_ms: float
    jitter_ms: float
    packet_loss_pct: float
    throughput_mbps: float
    bandwidth_utilisation_pct: float
    signal_quality: float
    availability_pct: float
    scenario_label: str

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        ts = self.timestamp
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        payload["timestamp"] = ts.isoformat().replace("+00:00", "Z")
        return payload

    def to_csv_row(self) -> dict[str, Any]:
        row = self.to_dict()
        return row


@dataclass
class NetworkEvent:
    """Ground-truth incident window generated by the scenario engine."""

    node_code: str
    event_type: str
    severity: str
    start_time: datetime
    description: str
    end_time: datetime | None = None
    event_id: str = field(default="")

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        for key in ("start_time", "end_time"):
            value = payload[key]
            if isinstance(value, datetime):
                if value.tzinfo is None:
                    value = value.replace(tzinfo=timezone.utc)
                payload[key] = value.isoformat().replace("+00:00", "Z")
        return payload


@dataclass
class ActiveScenario:
    """Currently active degradation scenario for a node."""

    scenario: ScenarioType
    severity: Severity
    started_at: datetime
    ends_at: datetime
    description: str
